private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

rpc:
  "local": "http://localhost:8545"
  "alchemy": "https"
  "goerli": "https"

metadata:
  diamond: "./contracts/out/Diamond.sol/Diamond.json"
  diamond_init: "./contracts/out/DiamondInit.sol/DiamondInit.json"
  cut_facet: "./contracts/out/DiamondCutFacet.sol/DiamondCutFacet.json"
  loupe_facet: "./contracts/out/DiamondLoupeFacet.sol/DiamondLoupeFacet.json"
  test: "./contracts/out/Test1Facet.sol/Test1Facet.json"

diamond_address: "0xCAFEBABECAFEBABECAFEBABECAFEBABECAFEBABE"